name: Update README and status

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "17 * * * *"

permissions: write-all

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x

      - name: install cog
        run: pip install cogapp

      - name: get omg.lol status
        id: extract
        uses: lucasmelin/omg.lol-gh-status-sync-action@v1.0.0
        with:
          omg_lol_user: lucasmelin
          github_token: ${{ secrets.PERSONAL_TOKEN }}

      - name: generate readme
        run: cog -r README.md
        env:
          emoji: ${{ steps.extract.outputs.emoji }}
          message: ${{ steps.extract.outputs.message }}

      - name: commit changes
        run: |
          git diff
          git config --global user.name 'Lucas Melin'
          git config --global user.email 'lucasmelin@users.noreply.github.com'
          git add -A
          git commit -m ":robot: Automated README update" || exit 0
          git push
